plugins {
    id 'org.springframework.boot' version '3.5.8' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

group = 'com.ravstore'
version = '0.0.1-SNAPSHOT'

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    configurations {
        mockitoAgent
    }

    dependencies {
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        mockitoAgent('org.mockito:mockito-core') { transitive = false }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        jvmArgs "-javaagent:${configurations.mockitoAgent.singleFile.absolutePath}"
    }
}
