spring.application.name=product-service
server.error.include-message=always
logging.level.root= ${LOG_LEVEL:INFO}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:ravstore}
spring.datasource.username=${POSTGRES_USER:ravstore}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jooq.sql-dialect=POSTGRES

