spring.application.name=product-service
server.error.include-message=always
logging.level.root= ${LOG_LEVEL:INFO}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}
